[project]
name = "fiap-tech-challenge"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.0.0",
    "bitsandbytes>=0.45.0",
    "datasets>=4.5.0",
    "faiss-cpu>=1.13.2",
    "google-cloud-storage>=2.14.0",
    "google-cloud-firestore>=2.14.0",
    "google-cloud-texttospeech>=2.36.0",
    "google-genai>=1.56.0",
    "ipython>=9.9.0",
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "langchain-text-splitters>=1.1.1",
    "langgraph>=1.0.10",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "pypdf>=6.7.4",
    "peft>=0.13.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "scikit-learn>=1.8.0",
    "sentence-transformers>=5.2.3",
    "streamlit>=1.52.2",
    "torch>=2.10.0",
    "transformers>=5.2.0",
    "torch>=2.4.0",
    "langchain-huggingface>=1.2.1",
    "grandalf>=0.8",
    "pygame-ce>=2.5.7",
    "google-cloud-videointelligence>=2.19.0",
    "pandas>=2.3.3",
]
